### ISSUE TITLE
Format-pester fails if all tests passed

### ISSUE THREAD

**Issue by TravisEz13** [equelin/Format-Pester#1]

**Comment by TravisEz13** [comment]
Added a test in my own branch with no code changes.  See the test results here:
https://ci.appveyor.com/project/TravisEz13/format-pester/build/1.0.11 
Branch is here:
https://github.com/TravisEz13/Format-Pester/tree/OldCodeWithNewTests

**Comment by equelin** [comment]
Good catch ! 
I'll merge your PR because I don't want to have does kind of bug in the master branch.
