### ISSUE TITLE
Non English chars are not correctly displayed for text output file

### ISSUE THREAD

**Issue by it-praktyk** [equelin/Format-Pester#12]
Like on the screenshot below - Polish chars are not correctly displayed - but only for text format.
![format-pester-text-results-for-polish](https://cloud.githubusercontent.com/assets/4910261/17652029/28dd5410-6273-11e6-831f-fb366254cb33.png)

The example based on the version 1.3.0 - the pull request #10

CC: @iainbrighton

**Comment by it-praktyk** [comment]
I've checked encoding of file containing Polish translation - UTF-8 is used.

**Comment by it-praktyk** [comment]
I've analyzed the code of PScribo 

``` powershell
## Text encoding
[Parameter(ValueFromPipelineByPropertyName)]
[ValidateSet('ASCII','Unicode','UTF7','UTF8')]
[System.String] $Encoding = 'ASCII'
```

[Source:](https://github.com/iainbrighton/PScribo/blob/dev/Src/Plugins/OutText.Internal.ps1#L37-L40)

Looks like that encoding parameter should be added to translations files also. 

Maybe I missed something but encoding is only used for text output. @iainbrighton, am I right?

**Comment by iainbrighton** [comment]
@it-praktyk The `Encoding` option is only used for the Text plugin. By default, ASCII encoding is used. Are you saying that the generated text file is in UTF8 encoding by default? For those Polish characters, will UTF8 format work or will you need Unicode?

**Comment by it-praktyk** [comment]
@ianbrighton,
- Polish letters can be encoded by UTF8 also
- the file what contains Polish translation is encoded by UTF8, not the result files

I know that I can add Encoding to the [section](equelin/Format-Pester/blob/master/Format-Pester/Public/Format-Pester.ps1#L184-L189) but I don't understand (is it too late or I'm too tired?) why a double hash table construction is used. Can you help me directly?
