### ISSUE TITLE
Please create releases for the version published to PowerShell Gallery

### ISSUE THREAD

**Issue by it-praktyk** [equelin/Format-Pester#13]
Like in the subject. It allow truck changes between two sources of Format-Pester code.

Thank you.

**Comment by equelin** [comment]
Hello @it-praktyk , Sorry but I'm not sure to understand what you're asking for. Could you be more specific ?

**Comment by it-praktyk** [comment]
@equelin with creating [the relase 1.3.1](https://github.com/equelin/Format-Pester/releases/tag/v1.3.1) you did exactly what I asked. 

Thanks
