### ISSUE TITLE
Inconclusive Test Error

### ISSUE THREAD

**Issue by vrdse** [equelin/Format-Pester#41]
Whenever I run `Invoke-Pester '\\server\Script.Tests.ps1' -PassThru | Format-Pester -Format HTML -Path $env:TEMP -BaseFileName $env:COMPUTERNAME`, I receive the following error

    PSMessageDetails      : 
    Exception             : System.Management.Automation.PropertyNotFoundException: The property "Inconclusive Tests" was not found for this Object. Make sure the property is available.
                               at System.Management.Automation.Language.PSGetMemberBinder.GetAdaptedValue(Object obj, String member)
                               at CallSite.Target(Closure , CallSite , Object )
                               at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
                               at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
    TargetObject          : 
    CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    FullyQualifiedErrorId : PropertyNotFoundStrict
    ErrorDetails          : 
    InvocationInfo        : System.Management.Automation.InvocationInfo
    ScriptStackTrace      : at GetHtmlTable<Process>, <No File>: Line 632
                            at OutHtmlTable<Process>, <No File>: Line 710
                            at OutHtmlSection<Process>, <No File>: Line 425
                            at OutHtml<Process>, <No File>: Line 65
                            at Export-Document<Process>, <No File>: Line 64
                            at Format-Pester, \\server\Format-Pester\1.6.0\Public\Format-Pester.ps1: Line 778
                            at <ScriptBlock>, <No File>: Line 1
    PipelineIterationInfo : {}

(I manually translated the error message)
I do not receive the error if I specify the `-Include` parameter without `Summary`. The summary table is created just fine despite the error message. I don't have any inconclusive test.

**Comment by it-praktyk** [comment]
Please provide the version number of the Pester module used?

**Comment by vrdse** [comment]
Pester version is 3.4.0.

**Comment by it-praktyk** [comment]
Please switch to Pester 4.x (preferably at least 4.1.1) and confirm that issue exist on that version too.

**Comment by vrdse** [comment]
I can confirm that it works fine with Pester 4.4.4. I'd love to see downwards compatibility. :) Any chance this get's fixed? As I said before, the report looks perfectly fine, it's just the error that is a bit "ugly".

**Comment by it-praktyk** [comment]
Pester 3.x [is dead. ](https://github.com/pester/Pester/tree/V3Maintenance). Please don't expect too much ;-).

**Comment by vrdse** [comment]
I can see your point. Though its what comes by default with Windows 10. ;) 
I just saw that you already have Pester 4 defined as a requirement, hence I'll close the issue. Thank you for the quick responses!
