### ISSUE TITLE
'Inconclusive Tests' error for formats other than Text

### ISSUE THREAD

**Issue by allywilson** [equelin/Format-Pester#43]
I receive the below error when I run **Format-Pester** with the **-Format HTML** or **-Format Word** switches:

> The property 'Inconclusive Tests' cannot be found on this object. Verify that the property exists.
> At line:632 char:25
> \+                         $rowPropertyName = $row.$propertyName; ## Cor ...
> \+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     \+ CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
>     \+ FullyQualifiedErrorId : PropertyNotFoundStrict

If I use **-Format Text** I get no error.

The output of all 3 is fine even though it does provide stdout error.

**Comment by it-praktyk** [comment]
Please provide versions of used
- PowerShell
- Pester
- Format-Pester

Thank you.

**Comment by allywilson** [comment]
Powershell: 5.1.14393.3053
Pester: 3.4.0
Format-Pester: 1.6.0

**Comment by it-praktyk** [comment]
@allywilson,
please upgrade Pester to version the newest version. Pester 3.x is not supported by Format-Pester.

Thank you for your understanding.

**Comment by allywilson** [comment]
Apologies for the slow response, I forgot to check. 

I've just upgraded to Pester 4.9.0 and it's working fine, thank you.
