### ISSUE TITLE
Output only success or failed tests results

### ISSUE THREAD

**Issue by it-praktyk** [equelin/Format-Pester#6]
Enhancement proposal.

Add switches and parameter sets to allow output/format only success/fail tests results.

Thx.

**Comment by equelin** [comment]
This is a good idea ! 
Could you be a litle bit more specific ? When outputting only success/failed results do you still want to see a resume of the tests ?

**Comment by it-praktyk** [comment]
Hi,
I think that for summary we can add the another one parameter :-)

Did you start maybe this enhancement? I would not like replicate your work.

**Comment by equelin** [comment]
Hello,
OK, I see what you mean.
I did not work on that for now and I don't think I will do it in the next week so feel free to provide a PR !

Thanks

**Comment by it-praktyk** [comment]
I implemented additional parameters. Please check/test https://github.com/it-praktyk/Format-Pester/tree/dev

**Comment by equelin** [comment]
Thank you @it-praktyk !

Feel free to do a PR, I'll merge it.

**Comment by it-praktyk** [comment]
Hi @equelin,
I just added some new features to my repo. If is it possible please test before I'll do PR.

Thanks.

**Comment by it-praktyk** [comment]
The new functionalities added in the pull request #8

**Comment by equelin** [comment]
I've merged your PR, thanks for your work @it-praktyk !
