### ISSUE TITLE
The selected license for Format-Pester is unclear

### ISSUE THREAD

**Issue by it-praktyk** [equelin/Format-Pester#7]
An information about license in the file Format-Pester.ps1
`
.NOTES
Written by Erwan Quelin and the community under Apache licence
`
but LICENSE file contains the MIT License (MIT).

Please select the one license for the project.

**Comment by equelin** [comment]
Good catch !

I'll correct this ASAP.

**Comment by equelin** [comment]
Corrected in the commit 4b807c4

Thanks @it-praktyk !
