### ISSUE TITLE
Format-Pester - translate static string (internationalization) - how implement (?) - RFC

### ISSUE THREAD

**Issue by it-praktyk** [equelin/Format-Pester#9]
Hi,
In the dev branch of my Format-Pester fork you can find partially rewrote code https://github.com/it-praktyk/Format-Pester/blob/dev/Format-Pester/Public/Format-Pester.ps1. 

In that version
- I added Order parameter - used to select if passed/failed tests are displayed as the first
- merged into the one 'branch' code for failed/passed code and put it in a loop
-  moved all static string to separate variables.

Options for prepare internationalization of Format-Pester
1. Variables with string can be moved now to separate Private function with a parameter "Language" and function dot sourced
2. http://community.bartdesmet.net/blogs/bart/archive/2008/03/23/windows-powershell-2-0-feature-focus-script-internationalization.aspx 

Any other ideas?

**Comment by it-praktyk** [comment]
@equelin , could you test dev branch in my fork ?

Translation to French will be helpful for that test ;-)

Thx.

**Comment by equelin** [comment]
Hello @it-praktyk 

I'm sorry but I'm short in time. I'll be in holidays at the end of the week so... 
I'll try to check your dev branch tomorow.

**Comment by equelin** [comment]
It's a really good idea, nice work!
@it-praktyk Please submit a PR.

**Comment by it-praktyk** [comment]
I'll prepare Pester tests to validate translations (structure of files) first.

**Comment by it-praktyk** [comment]
After merging my pull request #10 you can close that issue.
